const screens=[...document.querySelectorAll(".screen")],noBtn=document.getElementById("noBtn"),noMessage=document.getElementById("noMessage");
let noClicks=0,selectedFood="";
function show(n){screens.forEach((s,i)=>s.classList.toggle("active",i===n))}
noBtn.onclick=()=>{noClicks++;const sizes=[.88,.74,.60,.46,.27];noBtn.style.transform=`scale(${sizes[Math.min(noClicks-1,4)]})`;noMessage.textContent=["مطمئنی؟ 🥺","یه بار دیگه فکر کن...","نه رو چرا می‌زنی؟ 😭","این دکمه داره کوچیک میشه!","دیگه خیلی کوچیک شد..."][Math.min(noClicks-1,4)]};
document.getElementById("yesBtn").onclick=()=>show(1);
document.getElementById("nextBtn").onclick=()=>{if(!dateInput.value||!timeInput.value){noMessage.textContent="لطفاً تاریخ و ساعت رو انتخاب کن 🥺";return}show(2)};
document.querySelectorAll(".food").forEach(b=>b.onclick=()=>{document.querySelectorAll(".food").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedFood=b.dataset.food});
document.getElementById("goBtn").onclick=()=>{if(!selectedFood)return;const d=new Date(dateInput.value+"T00:00:00"),days=["یکشنبه","دوشنبه","سه‌شنبه","چهارشنبه","پنجشنبه","جمعه","شنبه"],months=["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"],p=dateInput.value.split("-").map(Number);document.getElementById("finalDate").textContent=`پس ${days[d.getDay()]} ${p[2]} ${months[p[1]-1]||p[1]} ساعت ${timeInput.value} میام دنبالت، برای ${selectedFood} 🥂`;show(3);setTimeout(()=>{lastMessage.textContent="میدونی خیلی دوست دارمم ❤️";lastMessage.classList.add("show")},900)};
for(let i=0;i<22;i++){let e=document.createElement("span");e.className="floating-heart";e.textContent=["❤️","💕","💗","💖","💓","💞"][Math.random()*6|0];e.style.cssText=`--left:${Math.random()*100}%;--size:${14+Math.random()*25}px;--opacity:${.18+Math.random()*.35};--duration:${7+Math.random()*8}s;--drift:${-60+Math.random()*120}px;--blur:${Math.random()*.5}px;animation-delay:-${Math.random()*12}s`;hearts.appendChild(e)}
for(let i=0;i<7;i++){let e=document.createElement("span");e.className="floating-word";e.textContent="LOVE YOU MY HASTI❤️";e.style.cssText=`--left:${-10+Math.random()*85}%;--top:${8+Math.random()*82}%;--size:${14+Math.random()*10}px;--opacity:${.10+Math.random()*.13};--duration:${5+Math.random()*5}s;animation-delay:-${Math.random()*6}s`;loveWords.appendChild(e)}